// Generated by Protostub
// see more examples: https://github.com/lovelyoyrmia/protostub
// Implement your logic below

package client

import (
    pb "github.com/lovelyoyrmia/protostub/examples/pb"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

type CustomerServiceClient struct {
	Client pb.CustomerServiceClient
}

func InitCustomerServiceClient(url string) (*CustomerServiceClient, error) {
	cc, err := grpc.NewClient(url, grpc.WithTransportCredentials(insecure.NewCredentials()))

	if err != nil {
		return nil, err
	}

	c := CustomerServiceClient{
		Client: pb.NewCustomerServiceClient(cc),
	}

	return &c, nil
}