// Generated by Protostub
// see more examples: https://github.com/lovelyoyrmia/protostub
// Implement your logic below

package pb

import (
	"context"
	"log"
	pb "github.com/lovelyoyrmia/protostub/examples/pb"
)

// CustomerServiceImpl implements the gRPC service for CustomerServiceImpl.
// This is the server struct that will be used to implement the service methods.
type CustomerServiceImpl struct {
	pb.UnimplementedCustomerServiceServer
}

// GetCustomer handles requests for the GetCustomer method.
// It takes a GetCustomerRequest request and returns a GetCustomerResponse response.
func (s *CustomerServiceImpl) GetCustomer(ctx context.Context, req *pb.GetCustomerRequest) (*pb.GetCustomerResponse, error) {
	// TODO: Implement your logic here
	log.Println("Received request:", req)
	return &pb.GetCustomerResponse{}, nil
}

// NewCustomerServiceServer returns a new instance of CustomerServiceImpl.
// This is used to initialize the gRPC server with the service implementation.
func NewCustomerServiceServer() *CustomerServiceImpl {
	return &CustomerServiceImpl{}
}
